In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv("npr.csv")
df.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [3]:
df.iloc[0]

Article    In the Washington of 2016, even when the polic...
Name: 0, dtype: object

#  Preprocessing

In [4]:
#we can provide stopwords as 'english' in countvectorizer

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_df=0.90 , min_df=2 , stop_words='english')
dtm = cv.fit_transform(df['Article'])

In [6]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [7]:
type(dtm)

scipy.sparse.csr.csr_matrix

In [8]:
# Here 7 is an preassume no which is no of topics
from sklearn.decomposition import LatentDirichletAllocation
lda = LatentDirichletAllocation(n_components=7 ,random_state=42)

In [9]:
lda.fit_transform(dtm)

array([[1.61040465e-02, 6.83341493e-01, 2.25376318e-04, ...,
        2.99652737e-01, 2.25479379e-04, 2.25497980e-04],
       [3.63424997e-02, 8.86130697e-01, 4.40751747e-04, ...,
        7.57636804e-02, 4.40866779e-04, 4.40835574e-04],
       [3.28569485e-04, 6.96344889e-01, 3.28302105e-04, ...,
        3.02012902e-01, 3.28724083e-04, 3.28352652e-04],
       ...,
       [1.44467964e-02, 1.60696622e-01, 1.73678310e-01, ...,
        2.24636569e-02, 3.98728349e-04, 3.98359730e-04],
       [4.33560738e-04, 3.53196803e-02, 4.33022554e-04, ...,
        9.62512640e-01, 4.33971991e-04, 4.33490254e-04],
       [3.98777533e-01, 2.54376049e-04, 3.59290659e-01, ...,
        2.40914375e-01, 2.54445555e-04, 2.54253739e-04]])

In [10]:
len(cv.get_feature_names())

54777

In [11]:
import random 
for i in range(10):
    x = random.randint(0,54777)
    print(cv.get_feature_names()[x])

visualizations
rationalize
token
eggs
abrasive
bennett
meter
okla
internships
slush


In [12]:
import random 
for i in range(10):
    x = random.randint(0,54777)
    print(cv.get_feature_names()[x])

venn
undermine
peanuts
benefactor
walters
empowers
wargames
carrion
bundled
proximity


In [13]:
len(lda.components_)

7

In [14]:
#single topic
lda.components_[0]

array([8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
       1.43006821e-01, 1.42902042e-01, 1.42861626e-01])

In [15]:
len(lda.components_[0])

54777

In [16]:
topic0 = lda.components_[0]

In [17]:
type(topic0)

numpy.ndarray

In [18]:
topic0.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [19]:
#least represntive word for the topic
topic0[2475]

0.1428571430851871

In [20]:
#Most represntive word for the topic
topic0[42993]

6247.245510521027

In [21]:
topic0.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [22]:
index_imp_words = topic0.argsort()[-10:]

In [23]:
for i in index_imp_words:
    print(cv.get_feature_names()[i])

new
percent
government
company
million
care
people
health
said
says


In [24]:
for index,topic in enumerate(lda.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']


THE TOP 15 WORDS FOR TOPIC #1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']


THE TOP 15 WORDS FOR TOPIC #2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']


THE TOP 15 WORDS FOR TOPIC #3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']


THE TOP 15 WORDS FOR TOPIC #4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']


THE TOP 15 WORDS FOR TOPIC #5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 'think',

In [25]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [26]:
dtm.shape

(11992, 54777)

In [27]:
topic_results = lda.transform(dtm)
topic_results

array([[1.61040465e-02, 6.83341493e-01, 2.25376318e-04, ...,
        2.99652737e-01, 2.25479379e-04, 2.25497980e-04],
       [3.63424997e-02, 8.86130697e-01, 4.40751747e-04, ...,
        7.57636804e-02, 4.40866779e-04, 4.40835574e-04],
       [3.28569485e-04, 6.96344889e-01, 3.28302105e-04, ...,
        3.02012902e-01, 3.28724083e-04, 3.28352652e-04],
       ...,
       [1.44467964e-02, 1.60696622e-01, 1.73678310e-01, ...,
        2.24636569e-02, 3.98728349e-04, 3.98359730e-04],
       [4.33560738e-04, 3.53196803e-02, 4.33022554e-04, ...,
        9.62512640e-01, 4.33971991e-04, 4.33490254e-04],
       [3.98777533e-01, 2.54376049e-04, 3.59290659e-01, ...,
        2.40914375e-01, 2.54445555e-04, 2.54253739e-04]])

In [28]:
topic_results.shape

(11992, 7)

In [29]:
topic_results[0]

array([1.61040465e-02, 6.83341493e-01, 2.25376318e-04, 2.25369288e-04,
       2.99652737e-01, 2.25479379e-04, 2.25497980e-04])

In [30]:
np.argmax(topic_results[0])

1

In [31]:
df.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [32]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 3, 4, 0], dtype=int64)

In [33]:
df['topics'] = topic_results.argmax(axis=1)

In [34]:
df.head()

Article  topics
0  In the Washington of 2016, even when the polic...       1
1    Donald Trump has used Twitter  —   his prefe...       1
2    Donald Trump is unabashedly praising Russian...       1
3  Updated at 2:50 p. m. ET, Russian President Vl...       1
4  From photography, illustration and video, to d...       2

In [35]:
df.head(20)

Article  topics
0   In the Washington of 2016, even when the polic...       1
1     Donald Trump has used Twitter  —   his prefe...       1
2     Donald Trump is unabashedly praising Russian...       1
3   Updated at 2:50 p. m. ET, Russian President Vl...       1
4   From photography, illustration and video, to d...       2
5   I did not want to join yoga class. I hated tho...       3
6   With a   who has publicly supported the debunk...       3
7   I was standing by the airport exit, debating w...       2
8   If movies were trying to be more realistic, pe...       3
9   Eighteen years ago, on New Year’s Eve, David F...       2
10  For years now, some of the best, wildest, most...       5
11  For years now, some of the best, wildest, most...       5
12  The Colorado River is like a giant bank accoun...       2
13  For the last installment of NPR’s holiday reci...       2
14  Being overweight can raise your blood pressure...       3
15  Who’s the YouTube star of 2016? Adele singing ...       5
16  Here’s a quick roundup of some of the   you ma...       2
17  Ben Johnston doesn’t follow the rules of music...       5
18  David Bowie, Prince and George Michael are all...       5
19  In November, the typically straitlaced Office ...       1